name: integration
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:
env:
  GO_VERSION: '1.17'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-integration-${{ hashFiles('**/go.sum') }}
          restore-keys: go-integration-
      - run: scripts/github-actions-packages
      - run: scripts/github-actions-setup
      - run: make all test-binaries
      - run: sudo -E test/test_runner.sh
        env:
          JOBS: '2'
